import { describe, expect, it } from 'vitest';
import type { AuditResult } from '../../../src/analyzers/base/analyzer.interface';
import { exportCSV, exportMarkdown } from '../../../src/utils/export';

function createMockResult(): AuditResult {
  return {
    url: 'https://example.com',
    overallScore: 74,
    overallGrade: 'C',
    results: [
      { analyzer: 'performance', score: 85, grade: 'B', findings: [], data: {}, duration: 10 },
      { analyzer: 'seo', score: 62, grade: 'D', findings: [], data: {}, duration: 8 },
      { analyzer: 'accessibility', score: 78, grade: 'C', findings: [], data: {}, duration: 5 },
    ],
    allFindings: [
      {
        id: 'seo-missing-title',
        analyzer: 'seo',
        severity: 'critical',
        category: 'Meta Tags',
        title: 'Missing title tag',
        description: 'The page does not have a <title> tag.',
        recommendation: 'Add a descriptive title tag.',
        impact: 'high',
        effort: 'quick-fix',
      },
      {
        id: 'perf-lcp-slow',
        analyzer: 'performance',
        severity: 'warning',
        category: 'Core Web Vitals',
        title: 'LCP needs improvement',
        description: 'LCP is 3.2s.',
        recommendation: 'Optimize images.',
        impact: 'high',
        effort: 'moderate',
        value: '3.2s',
        expected: '< 2.5s',
      },
      {
        id: 'sec-missing-hsts',
        analyzer: 'security',
        severity: 'info',
        category: 'Headers',
        title: 'Consider HSTS preload',
        description: 'HSTS does not include preload.',
        recommendation: 'Add preload to HSTS.',
        impact: 'low',
        effort: 'quick-fix',
      },
    ],
    analyzedAt: '2026-04-14T15:30:00.000Z',
  };
}

describe('exportCSV', () => {
  it('should include header row', () => {
    const csv = exportCSV(createMockResult());
    const firstLine = csv.split('\n')[0];
    expect(firstLine).toContain('Analyzer');
    expect(firstLine).toContain('Severity');
    expect(firstLine).toContain('Title');
  });

  it('should have correct number of rows', () => {
    const csv = exportCSV(createMockResult());
    const lines = csv.split('\n');
    expect(lines.length).toBe(4); // header + 3 findings
  });

  it('should escape commas in values', () => {
    const result = createMockResult();
    result.allFindings[0].description = 'Has a comma, in the text';
    const csv = exportCSV(result);
    expect(csv).toContain('"Has a comma, in the text"');
  });

  it('should include all finding fields', () => {
    const csv = exportCSV(createMockResult());
    expect(csv).toContain('seo');
    expect(csv).toContain('critical');
    expect(csv).toContain('Missing title tag');
  });

  it('should include value and expected columns', () => {
    const csv = exportCSV(createMockResult());
    expect(csv).toContain('3.2s');
    expect(csv).toContain('< 2.5s');
  });
});

describe('exportMarkdown', () => {
  it('should include report header', () => {
    const md = exportMarkdown(createMockResult());
    expect(md).toContain('# WebScope Audit Report');
    expect(md).toContain('https://example.com');
    expect(md).toContain('74/100 (C)');
  });

  it('should include scores table', () => {
    const md = exportMarkdown(createMockResult());
    expect(md).toContain('## Scores by Category');
    expect(md).toContain('| Performance | 85 | B |');
    expect(md).toContain('| SEO | 62 | D |');
  });

  it('should group findings by severity', () => {
    const md = exportMarkdown(createMockResult());
    expect(md).toContain('## Critical Findings (1)');
    expect(md).toContain('## Warnings (1)');
    expect(md).toContain('## Info (1)');
  });

  it('should include finding details', () => {
    const md = exportMarkdown(createMockResult());
    expect(md).toContain('Missing title tag');
    expect(md).toContain('Add a descriptive title tag.');
  });

  it('should include value and expected in findings', () => {
    const md = exportMarkdown(createMockResult());
    expect(md).toContain('**Current:** 3.2s');
    expect(md).toContain('**Expected:** < 2.5s');
  });

  it('should include footer with WebScope attribution', () => {
    const md = exportMarkdown(createMockResult());
    expect(md).toContain('Generated by [WebScope]');
  });

  it('should not include empty severity sections', () => {
    const result = createMockResult();
    result.allFindings = result.allFindings.filter((f) => f.severity !== 'info');
    const md = exportMarkdown(result);
    expect(md).not.toContain('## Info');
  });
});
