/**
 * Export utilities — generate CSV and Markdown from audit results.
 * Runs entirely client-side (no server needed).
 */

import type { AuditResult } from '../analyzers/base/analyzer.interface';

// --- CSV ---

export function exportCSV(result: AuditResult): string {
  const headers = [
    'Analyzer',
    'Severity',
    'Category',
    'Title',
    'Description',
    'Recommendation',
    'Impact',
    'Effort',
    'Current Value',
    'Expected Value',
  ];

  const rows = result.allFindings.map((f) => [
    f.analyzer,
    f.severity,
    f.category,
    csvEscape(f.title),
    csvEscape(f.description),
    csvEscape(f.recommendation),
    f.impact,
    f.effort,
    csvEscape(f.value || ''),
    csvEscape(f.expected || ''),
  ]);

  return [headers.join(','), ...rows.map((r) => r.join(','))].join('\n');
}

function csvEscape(str: string): string {
  if (str.includes(',') || str.includes('"') || str.includes('\n')) {
    return `"${str.replace(/"/g, '""')}"`;
  }
  return str;
}

// --- Markdown ---

export function exportMarkdown(result: AuditResult): string {
  const lines: string[] = [];
  const date = new Date(result.analyzedAt).toLocaleString();

  lines.push('# WebScope Audit Report');
  lines.push('');
  lines.push(`**URL:** ${result.url}`);
  lines.push(`**Date:** ${date}`);
  lines.push(`**Overall Score:** ${result.overallScore}/100 (${result.overallGrade})`);
  lines.push('');

  // Scores table
  lines.push('## Scores by Category');
  lines.push('');
  lines.push('| Category | Score | Grade |');
  lines.push('|---|---|---|');
  const names: Record<string, string> = {
    performance: 'Performance',
    seo: 'SEO',
    accessibility: 'Accessibility',
    content: 'Content',
    branding: 'Branding',
    security: 'Security',
  };
  for (const r of result.results) {
    lines.push(`| ${names[r.analyzer] || r.analyzer} | ${r.score} | ${r.grade} |`);
  }
  lines.push('');

  // Findings by severity
  const severities: Array<{ key: string; label: string }> = [
    { key: 'critical', label: 'Critical Findings' },
    { key: 'warning', label: 'Warnings' },
    { key: 'info', label: 'Info' },
    { key: 'pass', label: 'Passed Checks' },
  ];

  for (const { key, label } of severities) {
    const findings = result.allFindings.filter((f) => f.severity === key);
    if (findings.length === 0) continue;

    lines.push(`## ${label} (${findings.length})`);
    lines.push('');

    for (const f of findings) {
      lines.push(`### [${names[f.analyzer] || f.analyzer}] ${f.title}`);
      lines.push('');
      lines.push(f.description);
      if (f.value || f.expected) {
        const parts: string[] = [];
        if (f.value) parts.push(`**Current:** ${f.value}`);
        if (f.expected) parts.push(`**Expected:** ${f.expected}`);
        lines.push('');
        lines.push(parts.join(' | '));
      }
      lines.push('');
      lines.push(`> **Recommendation:** ${f.recommendation}`);
      if (f.impact || f.effort) {
        lines.push(`> Impact: ${f.impact} | Effort: ${f.effort}`);
      }
      lines.push('');
    }
  }

  lines.push('---');
  lines.push(`*Generated by [WebScope](https://webscope.sal.dev.br) on ${date}*`);

  return lines.join('\n');
}

// --- Download helper ---

export function downloadFile(content: string, filename: string, mimeType: string): void {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

export function downloadCSV(result: AuditResult): void {
  const csv = exportCSV(result);
  const domain = new URL(result.url).hostname.replace(/\./g, '-');
  downloadFile(csv, `webscope-${domain}.csv`, 'text/csv;charset=utf-8');
}

export function downloadMarkdown(result: AuditResult): void {
  const md = exportMarkdown(result);
  const domain = new URL(result.url).hostname.replace(/\./g, '-');
  downloadFile(md, `webscope-${domain}.md`, 'text/markdown;charset=utf-8');
}

// --- PDF ---

export function downloadPDF(): void {
  window.print();
}
